export const words = [
  "TELÉFONO MÓVIL", "CARGADOR", "AURICULARES", "CARTERA", "LLAVES", "GAFAS DE SOL", 
  "RELOJ", "BOLÍGRAFO", "CUADERNO", "TAZA", "VASO", "PLATO", "CUCHARA", "TENEDOR", 
  "CUCHILLO", "SERVILLETTA", "BOTELLA DE AGUA", "MOCHILA", "BOLSO", "PARAGUAS", "ABRIGO", 
  "ZAPATOS", "CALCETINES", "CAMISETA", "PANTALONES", "SUDADERA", "LIBRO", "REVISTA", 
  "MANDO A DISTANCIA", "TELEVISIÓN", "SOFÁ", "COJÍN", "MANTA", "LÁMPARA", "MESA", 
  "SILLA", "ALFOMBRA", "CORTINAS", "ESPEJO", "CEPILLO DE DIENTES", "PASTA DE DIENTES", 
  "JABÓN", "CHAMPÚ", "TOALLA", "SECADOR DE PELO", "PEINE", "MAQUINILLA DE AFEITAR", 
  "PAPEL HIGIÉNICO", "BOTE DE BASURA", "ESCOBA", "FREGONA", "CUBO", "DETERGENTE", 
  "ESPONJA", "LAVADORA", "NEVERA", "MICROONDAS", "HORNO", "CAFETERA", "TOSTADORA", 
  "SARTÉN", "OLLA", "ESPÁTULA", "TABLA DE CORTAR", "CESTA DE LA COMPRA", 
  "CARRITO DE LA COMPRA", "BILLETERA", "MONEDERO", "TARJETA DE CRÉDITO", "BILLETE", 
  "MONEDA", "PERCHA", "ARMARIO", "CAJÓN", "CAMA", "ALMOHADA", "SÁBANA", 
  "COLCHÓN", "DESPERTADOR", "RADIADOR", "AIRE ACONDICIONADO", "CALENDARIO", "MARCO DE FOTOS", 
  "VELA", "MECHERO", "TIJERAS", "PEGAMENTO", "CINTA ADHESIVA", "DESTORNILLADOR", "MARTILLO", 
  "CLAVO", "TORNILLO", "BOMBILLA", "PILA", "LINTERNA", "GOMA DE BORRAR", 
  "SACAPUNTAS", "LÁPIZ", "ROTULADOR", "PIZARRA"
];